id: A20F69AEA
title: Prayer to Avalokiteśvara
type: translation
pechas:
- I9B02CB02
- ID6D22336
- ID81D423B
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:43:11.218006
  last_modified_at: 2023-01-04 11:43:11.218036
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I9B02CB02/F1FA: '4006'
  ID6D22336/1F28: '4006'
  ID81D423B/82C3: '4006'
